// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBjGbQdCK4dAc9oEiqNM2aR4fb6p4g9KQ',
    appId: '1:478038084614:android:50f10843c82b5e2d394787',
    messagingSenderId: '478038084614',
    projectId: 'shoppingapp-7e17f',
    storageBucket: 'shoppingapp-7e17f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSg0h6A5G9cSz3RLjge2LcIzjElZXbN7g',
    appId: '1:478038084614:ios:2624ab1521a48512394787',
    messagingSenderId: '478038084614',
    projectId: 'shoppingapp-7e17f',
    storageBucket: 'shoppingapp-7e17f.firebasestorage.app',
    androidClientId: '478038084614-1uh1s9cpshk6835ha2mjisbvmk464k3p.apps.googleusercontent.com',
    iosClientId: '478038084614-sfcsi3ojjjidkqp9e6361dapt95dedpm.apps.googleusercontent.com',
    iosBundleId: 'com.majd.ecommerce.ecommerceApp',
  );

}